// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3cMXO9gZ3BOnEJ2vhbj0h88Qprtcx5U',
    appId: '1:229181566236:web:425582f7fbb6e369d85ed9',
    messagingSenderId: '229181566236',
    projectId: 'saasify-de974',
    authDomain: 'saasify-de974.firebaseapp.com',
    storageBucket: 'saasify-de974.appspot.com',
    measurementId: 'G-E3KFR14ZEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60L2rPsek82Up0JBvXk8sBJNnHaYx3R8',
    appId: '1:229181566236:android:251087f923f72a42d85ed9',
    messagingSenderId: '229181566236',
    projectId: 'saasify-de974',
    storageBucket: 'saasify-de974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhU7aSe5a8KJ0IHV1Nvmq6zWDM96NYze0',
    appId: '1:229181566236:ios:7358bef77938b9c8d85ed9',
    messagingSenderId: '229181566236',
    projectId: 'saasify-de974',
    storageBucket: 'saasify-de974.appspot.com',
    iosBundleId: 'com.example.saasify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhU7aSe5a8KJ0IHV1Nvmq6zWDM96NYze0',
    appId: '1:229181566236:ios:ec2452acf89aff49d85ed9',
    messagingSenderId: '229181566236',
    projectId: 'saasify-de974',
    storageBucket: 'saasify-de974.appspot.com',
    iosBundleId: 'com.example.saasify.RunnerTests',
  );
}
